{{- if .Values.ksocGuard.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ksoc-guard
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-guard
    app_version: {{ .Values.ksocGuard.image.tag | quote }}
    maintained_by: ksoc
spec:
  dnsNames:
  - ksoc-guard.{{ .Release.Namespace }}.svc
  - ksoc-guard.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: ksoc-selfsigned-issuer
  secretName: ksoc-guard-self-signed-cert
{{- end -}}
