{{- if .Values.ksocGuard.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ksoc-guard
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/ksoc-guard
  labels:
    app_name: ksoc-guard
    app_version: {{ .Values.ksocGuard.image.tag | quote }}
    maintained_by: ksoc
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: ksoc-guard
        namespace: {{ .Release.Namespace }}
        path: /mutate
    failurePolicy: Ignore
    timeoutSeconds: {{ .Values.ksocGuard.webhook.timeoutSeconds }}
    name: guard.ksoc.com
    {{- with .Values.ksocGuard.webhook.objectSelector}}
    objectSelector:
{{ toYaml . | indent 6 }}
    {{- end }}
    rules:
      - apiGroups: [ "apps" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE", "UPDATE" ]
        resources: [ "daemonsets", "deployments", "statefulsets" ]
      - apiGroups: [ "batch" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE", "UPDATE" ]
        resources: [ "jobs", "cronjobs" ]
      - apiGroups: [ "rbac.authorization.k8s.io" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE", "UPDATE" ]
        resources: [ "rolebindings", "clusterrolebindings", "roles", "clusterroles" ]
      - apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE", "UPDATE" ]
        resources: [ "pods", "namespaces" ]
    sideEffects: NoneOnDryRun
{{- end -}}
