{{- if .Values.ksocSbom.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksoc-sbom
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-sbom
    app_version: {{ .Values.ksocSbom.image.tag | quote }}
    maintained_by: ksoc
spec:
  minReadySeconds: 90
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app_name: ksoc-sbom
  template:
    metadata:
      labels:
        app_name: ksoc-sbom
        app_version: {{ .Values.ksocSbom.image.tag | quote }}
        maintained_by: ksoc
      annotations:
        {{- if .Values.deployments.disableServiceMesh }}
        linkerd.io/inject: disabled
        sidecar.istio.io/inject: "false"
        {{- end }}
        {{- with .Values.ksocSbom.podAnnotations }}
{{ toYaml . | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: ksoc-sbom
      {{- if .Values.deployments.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.deployments.imagePullSecretName }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: ksoc-bootstrapper
          image: {{ .Values.ksocBootstrapper.image.repository }}:{{ .Values.ksocBootstrapper.image.tag }}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: AGENT_VERSION
              value: {{ .Values.ksocBootstrapper.image.tag | quote }}
            - name: CHART_VERSION
              value: {{ .Chart.Version }}
            - name: KSOC_API_URL
              value: {{ .Values.ksoc.apiUrl }}
            - name: KSOC_CLUSTER_NAME
              value: {{ .Values.ksoc.clusterName }}
            - name: KSOC_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: KSOC_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  {{ if .Values.ksoc.accessKeySecretNameOverride -}}
                  name: {{ .Values.ksoc.accessKeySecretNameOverride }}
                  {{ else -}}
                  name: ksoc-access-key
                  {{ end -}}
                  key: access-key-id
            - name: KSOC_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  {{ if .Values.ksoc.accessKeySecretNameOverride -}}
                  name: {{ .Values.ksoc.accessKeySecretNameOverride }}
                  {{ else -}}
                  name: ksoc-access-key
                  {{ end -}}
                  key: secret-key
      containers:
        - name: ksoc-sbom
          image: {{ .Values.ksocSbom.image.repository }}:{{ .Values.ksocSbom.image.tag }}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: AGENT_VERSION
              value: {{ .Values.ksocSbom.image.tag | quote }}
            - name: CHART_VERSION
              value: {{ .Chart.Version }}
            - name: KSOC_API_URL
              value: {{ .Values.ksoc.apiUrl }}
            - name: KSOC_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: KSOC_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  {{ if .Values.ksoc.accessKeySecretNameOverride -}}
                  name: {{ .Values.ksoc.accessKeySecretNameOverride }}
                  {{ else -}}
                  name: ksoc-access-key
                  {{ end -}}
                  key: access-key-id
            - name: KSOC_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  {{ if .Values.ksoc.accessKeySecretNameOverride -}}
                  name: {{ .Values.ksoc.accessKeySecretNameOverride }}
                  {{ else -}}
                  name: ksoc-access-key
                  {{ end -}}
                  key: secret-key
            {{- range $key, $value := .Values.ksocSbom.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
          - mountPath: /tmp
            name: temp-image-dir
            readOnly: false
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
          resources:
{{ toYaml .Values.ksocSbom.resources | indent 12 }}
        - name: kube-rbac-proxy
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
          args:
          - "--secure-listen-address=0.0.0.0:8443"
          - "--upstream=http://127.0.0.1:8080/"
          - "--logtostderr=true"
          - "--v=0"
          ports:
          - containerPort: 8443
            protocol: TCP
            name: https
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      {{- with .Values.deployments.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.deployments.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
  {{- end }}
      volumes:
      - name: temp-image-dir
        emptyDir: {}
      - name: cert
        secret:
          defaultMode: 420
          secretName: ksoc-sbom-self-signed-cert
{{- end -}}
