{{ if not (or .Values.ksoc.accessKeySecretNameOverride) }}
apiVersion: v1
kind: Secret
metadata:
  name: ksoc-access-key
  namespace: {{ .Release.Namespace }}
  labels:
    maintained_by: ksoc
data:
  access-key-id: {{ .Values.ksoc.base64AccessKeyId | quote }}
  secret-key:  {{ .Values.ksoc.base64SecretKey | quote }}
{{ end }}
